### ISSUE TITLE
how can this output pyc file transfer to readable python file?

### ISSUE THREAD

**Issue by huanzhiyi** [0x3C50/nofuscate#2]
I used this to format into a pyc file，and then use 'python-uncompyle6' to try,but it does not work!
Can you give me some help?

**Comment by 0x3C50** [comment]
The output is a compiled python file, uncompyle6 only supports python versions up to 3.9. Try using a tool like pycdas to get the assembly, or just specify "disassemnly" as the output type to get a disassembly directly.

**Comment by huanzhiyi** [comment]
> The output is a compiled python file, uncompyle6 only supports python versions up to 3.9. Try using a tool like pycdas to get the assembly, or just specify "disassemnly" as the output type to get a disassembly directly.

thanks for your help,i will find to try
