### ISSUE TITLE
你好 我这边遇到了个棘手的问题 可以帮我看一下代码吗

### ISSUE THREAD

**Issue by smallfawn** [0x3C50/nofuscate#3]
代码太长

**Comment by 0x3C50** [comment]
![grafik](https://github.com/user-attachments/assets/b0ea753a-6586-4825-970b-de344feb0f5e)
please speak english i cant see your chinese letters

**Comment by smallfawn** [comment]
I got an error on my end

I read the result of gzip.decompress and saved it to a file, but your program reads the file with an error src = inp_file.read().

UnicodeDecodeError: 'gbk' codec can't decode byte 0xa0 in position 82: illegal multibyte sequence
![QQ20241201-103458](https://github.com/user-attachments/assets/29ab7fae-5460-4a44-8dc4-6fc72efa15ce)

**Comment by smallfawn** [comment]
result 
![Uploading 结果.png…]()

**Comment by smallfawn** [comment]
![结果](https://github.com/user-attachments/assets/05437d8f-d738-41c5-b815-c6166df680d5)

**Comment by 0x3C50** [comment]
can you send me the original and deobfuscated code?

**Comment by 0x3C50** [comment]
i can't help without you giving me the original code. closing the issue for now, reopen when you reply.
